<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<Product>KittyCat</Product>
	<Company>PurrplingCat</Company>
	<Version>0.1.0-dev+42</Version>
	<RootNamespace>KittyCat</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
    <Platforms>AnyCPU</Platforms>
	<Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DotTiled" Version="0.3.0" />
    <PackageReference Include="Friflo.Engine.ECS" Version="3.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.7" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.7" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.*">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scrutor" Version="6.1.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\PurrplingCore.Ecs\PurrplingCore.Ecs.csproj" />
    <ProjectReference Include="..\..\PurrplingCore.Toolkit\PurrplingCore.Toolkit.csproj" />
  </ItemGroup>
</Project>
